// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfquprotnundnlklxact.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmcXVwcm90bnVuZG5sa2x4YWN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NzAxOTQsImV4cCI6MjA3MTM0NjE5NH0.Gg8UZ86vJMdVrBOuTGb0TgTT_1UCOPnHBt8k53Onajo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});